### ISSUE TITLE
[bug] runner width for ie8 differs to ie9

### ISSUE THREAD

**Issue by ndu** [richardscarrott/jquery-ui-carousel#48]
info: adding items to the runner may cause round problems in different browsers

method: _setRunnerWidth

old line: return self._getItemDim() \* self.getNoOfItems();

Solution:
new line: return Math.ceil(self._getItemDim() \* self.getNoOfItems());

**Comment by flachware** [comment]
hi @ndu,
my apologies, this might be considered inappropriate, but in the lack of other possibilities i’d like you to contact this way.

i would like to set up a github organization for a university that happens to be called 'ndu'. as i haven’t seen any other activity for your user name i was wondering if you would be willing to leave your user name to that organisation. if so, please contact me by email: johannes.krtek@flachware.com.

many thanks in advance!
