### ISSUE TITLE
can i used multiple slider in single page 

### ISSUE THREAD

**Issue by rohitya** [richardscarrott/jquery-ui-carousel#74]
Hi,

please help me i am using rs carousel but i can't use multiple carousel in one single page
 
please help me out .. how can i.

thanks

**Comment by richardscarrott** [comment]
Yes it will work as new instance will be created for each element:

```
    $('.rs-carousel-1').carousel();
    $('.rs-carousel-2').carousel();
```

Will result in two independent carousels and controls.

Can you provide some more information if you're having trouble with this?
