### ISSUE TITLE
Carousel function name too general, causes conflicts in Bootstrap

### ISSUE THREAD

**Issue by mokanfar** [richardscarrott/jquery-ui-carousel#79]
Thank you for your wonderful script and continued support! Bootstrap and a lot of other themes/frameworks use namespace "carousel" across class elements and vendor scripts. This as a result gets your script applied to undesired elements even though you have a unique class name itself ( $('.rs-carouselo').carousel(); ). I did a simple hack by renaming the carousel function/styling to make it work though. Is there a cleaner way to do this?

**Comment by richardscarrott** [comment]
I think you can change it's name by extending it, e.g.

```javascript
    $.widget('rs.foo', $.rs.carousel, {});
    $('.rs-carousel').foo();
```

Just make sure that is run before Bootstrap (or whatever carousel script is taking the `$.fn.carousel` namespace) is run.
